### ISSUE TITLE
Multiple errors in executing vcf2msa.py

### ISSUE THREAD

**Issue by DuttaAnik** [tkchafin/vcf2msa.py#2]
Hi, 
Thank you for developing this nifty tool. I installed all the tools as instructed but when I execute them, I received the following error message:

`python vcf2msa.py -f Ref.fasta -v Multi_sample.vcf.gz -r Chr_3:6009958-6011175 -m C004.mpileup -m C005.mpileup`
```
Reading reference sequence from /users/adutta/Genomes/Ref.fasta
Found samples: ['C004', 'C005', 'C006', 'C007', 'C008', 'C009', 'C012', 'C013', 'C014', 'C015', 'C018', 'C019', 'C020', 'C021', 'C023', 'C025', 'C026', 'C027', 'C028', 'C029', 'C030', 'C032', 'C033', 'C034', 'C035', 'C036', 'C037', 'C040', 'C041', 'C042', 'C044', 'C045', 'C046', 'C047', 'C048', 'C049', 'C052', 'C053', 'C054', 'C056', 'C057', 'C058', 'C059', 'C060', 'C061', 'C062', 'C063', 'C064', 'C067', 'C069', 'C070', 'C071', 'C072', 'C073', 'C074', 'C077', 'C078', 'C079', 'C081', 'C082', 'C083', 'C084', 'C085', 'C086', 'C087', 'C089', 'C090', 'C091', 'C092', 'C093', 'C094', 'C095', 'C096', 'C098', 'C099', 'C100', 'C101', 'C104', 'C105', 'C106', 'C107', 'C108', 'C109', 'C110', 'C111', 'C112', 'C113', 'C114', 'C115', 'C118', 'C119', 'C121', 'C122', 'C123', 'C124', 'C126', 'C127', 'C128', 'C129']
Traceback (most recent call last):
  File "/users/adutta/software/vcf2msa.py-master/vcf2msa.py", line 688, in <module>
    main()
  File "/users/adutta/software/vcf2msa.py-master/vcf2msa.py", line 87, in main
    for maskFile in params.mask:
AttributeError: 'parseArgs' object has no attribute 'mask'
```

If I delete the `mpileup` files with the flag `-m` and run the code without those, then again I receive an error message like:

```
Traceback (most recent call last):
  File "/users/adutta/software/vcf2msa.py-master/vcf2msa.py", line 688, in <module>
    main()
  File "/users/adutta/software/vcf2msa.py-master/vcf2msa.py", line 209, in main
    this_pos = muscle_align(this_pos)
  File "/users/adutta/software/vcf2msa.py-master/vcf2msa.py", line 376, in muscle_align
    records.add_sequence(key, seq)
AttributeError: 'MultipleSeqAlignment' object has no attribute 'add_sequence'
```

I checked the other issue posted here with the same error. I have Biopython installed in a `conda` environment and I am running the `vcf2msa.py` from a `conda` environment with `python version > 3`. Still, getting those errors. 

Can you please help me to correct those?
Thanks a lot.

**Comment by DuttaAnik** [comment]
Hi, sorry, I got it to work. Just created a conda environment for python 3 and everything was fine.

But I have another question. I have the mpileup data for 99 individuals and each of those mpileup file is around ~120 Gb size. Is there an option where I can provide a .txt file listing all the mpileup files rather than putting 99 individuals separately flagged by `-m`?

**Comment by tkchafin** [comment]
> Hi, sorry, I got it to work. Just created a conda environment for python 3 and everything was fine.

> But I have another question. I have the mpileup data for 99 individuals and each of those mpileup file is around` ~120 Gb size. Is there an option where I can provide a .txt file listing all the mpileup files rather than putting 99 individuals separately flagged by -m?


Hi, sorry for the delay, I just found this in my spam filter :) 

Glad you were able to get it to work! No, unfortunately right now I don't have an option for providing the list of files as text (although I agree it would make sense to do that). However, with all of the pileups being so large, you might want to loop through and generate the VCF for each sample individually, unless you are only generating MSAs for some regions? You could then merge those in vcftools/bcftools. 


If you do want to include them all, a workaround for now which wouldn't involve changing the code would be to build your command into a bash variable automatically, like:
```
FILES=`ls *.txt | awk -v ORS=" -m "  '{print}' | sed "s/-m $//g"` 

echo "-m $FILES"

-m adult.indGenDistMat.txt -m adult.isolationByDistance.txt -m adult.pointCoords.txt -m adult.snapDistances.txt -m adult.streamDistMat.txt -m juv.indGenDistMat.txt -m juv.isolationByDistance.txt -m juv.pointCoords.txt -m juv.snapDistances.txt -m juv.streamDistMat.txt -m juvpop.clusterCentroids.txt -m juvpop.incidenceMatrix.txt -m juvpop.isolationByDistance.txt -m juvpop.obsVersusFittedD.txt -m juvpop.pointCoords.txt -m juvpop.popGenDistMat.txt -m juvpop.popmap.txt -m juvpop.reachToEdgeTable.txt -m juvpop.snapDistances.txt -m juvpop.streamDistMat.txt -m juvpop.streamTree.txt -m out.indGenDistMat.txt -m out.pointCoords.txt -m out.snapDistances.txt 


```

**Comment by DuttaAnik** [comment]
Hi,

Ok thank you for the reply. But what about the other errors that I am getting? Could you please comment on that if you have any solution?

**Comment by tkchafin** [comment]
I think the "MultipleSeqAlignment has no attribute" may be a BioPython version issue. Could you try upgrading with `pip install biopython --upgrade`

**Comment by tkchafin** [comment]
fixed a bug causing the params.mask issue. run `git pull` to pull the newer vcf2msa.py

**Comment by DuttaAnik** [comment]
Ok. Let me try now.

**Comment by DuttaAnik** [comment]
Hi,
So the error still persists with the bug fixed version. Take a look

```
Traceback (most recent call last):
  File "/gxfs_home/cau/suaph275/vcf2msa.py-master/vcf2msa.py", line 685, in <module>
    main()
  File "/gxfs_home/cau/suaph275/vcf2msa.py-master/vcf2msa.py", line 209, in main
    this_pos = muscle_align(this_pos)
  File "/gxfs_home/cau/suaph275/vcf2msa.py-master/vcf2msa.py", line 376, in muscle_align
    records.add_sequence(key, seq)
AttributeError: 'MultipleSeqAlignment' object has no attribute 'add_sequence'
```

**Comment by DuttaAnik** [comment]
this is my command
`python /gxfs_home/cau/suaph275/vcf2msa.py-master/vcf2msa.py -f /gxfs_work1/cau/suaph275/Chilense_Hiseq/Bam_RG_files/S_chilense_Hirise.fasta -v Chilense_99.genotyped.SNP.Clean.MAF.MAXMiss.MinDP.recode.dustmasked.headers.vcf.gz -r Scaffold_9__1_contigs__length_70652527:6009958-6011175`

The `vcf.gz` is a multisample `vcf` file.

**Comment by tkchafin** [comment]
Ah ok, looks like the MultipleSeqRecord object might have changed a bit, and the online documentation doesn't match the latest version of the Biopython code. I just pushed a fix that is working for me

**Comment by DuttaAnik** [comment]
So, should I `git clone` the repo again?

**Comment by tkchafin** [comment]
yes

**Comment by DuttaAnik** [comment]
Ok. let me try

**Comment by DuttaAnik** [comment]
Hi,

Thank you so much. It has finally worked. Much appreciate your effort and responses.

**Comment by tkchafin** [comment]
Hi, no problem, glad you found the script useful
